c_stdlib_version:          # [osx]
  - '10.15'                # [osx]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.15'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and arm64]
  - '14.5'                 # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and arm64]
  - '14.0'                 # [osx and arm64]
