{% set name = "fpocket" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Discngine/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ca23d9c43dc7180c61fa0e035d1285213d16a1f219cfb262fa1579665a9fd6a6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libnetcdf

test:
  commands:
    - fpocket

about:
  home: https://github.com/Discngine/fpocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fpocket is a very fast open source protein pocket detection algorithm based on Voronoi tessellation
  doc_url: https://github.com/Discngine/fpocket/tree/master/doc
  dev_url: https://github.com/Discngine/fpocket

extra:
  recipe-maintainers:
    - simonbray
    - pschmidtke
