{% set name = "fpocket" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Discngine/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f90d86e474612a06ca7908771ae59effb23cea77c02b7df07bcdbb3ae08c2053

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libnetcdf

test:
  commands:
    - fpocket

about:
  home: https://github.com/Discngine/fpocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fpocket is a very fast open source protein pocket detection algorithm based on Voronoi tessellation
  doc_url: https://github.com/Discngine/fpocket/tree/master/doc
  dev_url: https://github.com/Discngine/fpocket

extra:
  recipe-maintainers:
    - simonbray
    - pschmidtke
