{% set name = "fpocket" %}
{% set version = "3.1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Discngine/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6a801c7a4af0f76a58369b558ca5f6674571e1825024d459bba20bc07ae4f8b7

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libnetcdf

test:
  commands:
    - fpocket

about:
  home: https://github.com/Discngine/fpocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fpocket is a very fast open source protein pocket detection algorithm based on Voronoi tessellation
  doc_url: https://github.com/Discngine/fpocket/tree/master/doc
  dev_url: https://github.com/Discngine/fpocket

extra:
  recipe-maintainers:
    - simonbray
    - pschmidtke
