travis:
  secure:
    BINSTAR_TOKEN: HkDY5SyAk8PTZsEqgO3vNk4UdFNEKHLNmsC7J+La0KFOfFYERp4J+07JWMzXjshXblr52JkXekppgT6+bGlFn3/ftz514YkjYI9B0KBUB76kWRQHSauuj8Dd3K5Br77mAred6e7CpQCkxu0uUdGcCTk7d8z4AYHq07QXNYRUsap55+S7SzI/XjU05TSP1EzfpyEIEwT7ezquArpsFqO0BEze9LcC1qH2ZT22OWKu9fDM5JcOa4HNtTmpfkBeu4ZBupirYaKkhaihEmdI8mj36TTXlDee0meLS5uIaqpyhC9GNjoEfeiLxvySReYcExJEbfOpPk0gXysZWHOzvDEWhHCLcC9hV5xpISRKvk8hPhWxaUlw+lkI5UyN+UIGBpzIvvVaKxa36hyp1QXLLpDaQMF2HyNG1xSCLy/8Ya6rY1+ZQQqLB4RtG/5uieTaGhmlxx/6shz1nOmW7scbcVNgqBAgNVGNBWVIvGgHKLCucggCVuuW/6sWfeOvfEjfYVivwBNxW/IZPD1DbdwVjYwp7juKmE62IpUHj0Ush6WwV3Bj9gIknjmmK1BFpD1jGcY3WK3htWv62rgDDWK7uii1wRHBML3tQqtEPcS1wbO4cU+VZKR3KOzNweWBovI5OnfmBdG1YeMdYlp8SmQWcyy/tpo0Q1teugLtXQ6Ful5UhHk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
